/* Generated By:JavaCC: Do not edit this line. parseConstants.java */

/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface parseConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 5;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 6;
  /** RegularExpression Id. */
  int LPAREN = 7;
  /** RegularExpression Id. */
  int RPAREN = 8;
  /** RegularExpression Id. */
  int ADD_OP = 9;
  /** RegularExpression Id. */
  int MULTIPLY = 10;
  /** RegularExpression Id. */
  int DIVIDE = 11;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 12;
  /** RegularExpression Id. */
  int CLASS = 13;
  /** RegularExpression Id. */
  int IF = 14;
  /** RegularExpression Id. */
  int ELSE = 15;
  /** RegularExpression Id. */
  int STRING = 16;
  /** RegularExpression Id. */
  int PUBLIC = 17;
  /** RegularExpression Id. */
  int STATIC = 18;
  /** RegularExpression Id. */
  int VOID = 19;
  /** RegularExpression Id. */
  int MAIN = 20;
  /** RegularExpression Id. */
  int THIS = 21;
  /** RegularExpression Id. */
  int PERIOD = 22;
  /** RegularExpression Id. */
  int WHILE = 23;
  /** RegularExpression Id. */
  int EXTENDS = 24;
  /** RegularExpression Id. */
  int BOOLEAN = 25;
  /** RegularExpression Id. */
  int TRUE = 26;
  /** RegularExpression Id. */
  int FALSE = 27;
  /** RegularExpression Id. */
  int INT = 28;
  /** RegularExpression Id. */
  int LENGTH = 29;
  /** RegularExpression Id. */
  int INT_ARRAY = 30;
  /** RegularExpression Id. */
  int NEW = 31;
  /** RegularExpression Id. */
  int NOT = 32;
  /** RegularExpression Id. */
  int EQUALS = 33;
  /** RegularExpression Id. */
  int COMMA = 34;
  /** RegularExpression Id. */
  int RETURN = 35;
  /** RegularExpression Id. */
  int IDENTIFIER = 36;
  /** RegularExpression Id. */
  int LBRACKET = 37;
  /** RegularExpression Id. */
  int RBRACKET = 38;
  /** RegularExpression Id. */
  int LCBRACKET = 39;
  /** RegularExpression Id. */
  int RCBRACKET = 40;
  /** RegularExpression Id. */
  int SEMICOLON = 41;
  /** RegularExpression Id. */
  int LESS_THAN = 42;
  /** RegularExpression Id. */
  int MORE_THAN = 43;
  /** RegularExpression Id. */
  int AND = 44;
  /** RegularExpression Id. */
  int PRINT = 45;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\" \"",
    "<SINGLE_LINE_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "\"(\"",
    "\")\"",
    "<ADD_OP>",
    "\"*\"",
    "\"/\"",
    "<INTEGER_LITERAL>",
    "\"class\"",
    "\"if\"",
    "\"else\"",
    "\"String\"",
    "\"public\"",
    "\"static\"",
    "\"void\"",
    "\"main\"",
    "\"this\"",
    "\".\"",
    "\"while\"",
    "\"extends\"",
    "\"boolean\"",
    "\"true\"",
    "\"false\"",
    "\"int\"",
    "\"length\"",
    "\"int []\"",
    "\"new\"",
    "\"!\"",
    "\"=\"",
    "\",\"",
    "\"return\"",
    "<IDENTIFIER>",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\"<\"",
    "\">\"",
    "\"&&\"",
    "\"System.out.println\"",
  };

}
